language: php
php:
  - 5.3
  - 5.4
before_script:
  - git submodule init
  - git submodule update
  - pear channel-discover zend.googlecode.com/svn
  - pear install zend/zend
script: phpunit --colors --bootstrap tests/bootstrap.php tests
