language: php
php:
  - 5.3
  - 5.4
before_script:
  - git submodule init
  - git submodule update
  - pyrus channel-discover zend.googlecode.com/svn
  - pyrus install zend/zend
  - phpenv rehash
script: phpunit --colors --bootstrap tests/bootstrap.php tests
